"""empty message

Revision ID: 1aaba381077a
Revises: 601a1ac07ca1
Create Date: 2019-01-05 13:24:44.659115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aaba381077a'
down_revision = '601a1ac07ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'uemail',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'upwd',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'upwd',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'uemail',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
