"""empty message

Revision ID: 66c128fad836
Revises: 25b99db067c4
Create Date: 2019-01-04 09:33:35.233846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c128fad836'
down_revision = '25b99db067c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('upsw', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('upsw', 'user', ['upsw'], unique=True)
    # ### end Alembic commands ###
